aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.0.0/25 --availability-zone ap-southeast-2a
aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.1.0/25 --availability-zone ap-southeast-2b
aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.2.0/25 --availability-zone ap-southeast-2a
aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.3.0/25 --availability-zone ap-southeast-2b
aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.4.0/25 --availability-zone ap-southeast-2a
aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.5.0/25 --availability-zone ap-southeast-2b
aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.6.0/25 --availability-zone ap-southeast-2a
aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.7.0/25 --availability-zone ap-southeast-2b
aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.8.0/25 --availability-zone ap-southeast-2a 
aws ec2 create-subnet --vpc-id vpc-vpcid --cidr-block 10.72.9.0/25 --availability-zone ap-southeast-2b 